### ISSUE TITLE
Package seems to be broken

### ISSUE THREAD

**Issue by Vitals9367** [voiceflow/react-chat#157]
Hey, tried to install the package and it seems to be broken.

![image](https://github.com/user-attachments/assets/2daab838-b7e4-4ae2-b00c-db9eac24f054)

**Comment by TheCenterforUnity** [comment]
I have the same issue. I'm stuck. Help, please!

**Comment by WillAIWorld** [comment]
I have the exact same error, found any solutions ?

**Comment by DecathectZero** [comment]
currently working on the fix, we'll make a dedicated public package for this.

**Comment by WillAIWorld** [comment]
> currently working on the fix, we'll make a dedicated public package for this.

No problem, i just fixed it, just needed to install back the react-chat : "npm i @voiceflow/react-chat@1.61.0" it wasn't up to date that's all, if anyone got that problem just check if everything is up to date.

**Comment by effervescentia** [comment]
sorry for the wait, the latest version no longer depends on the `@voiceflow/dtos` dependency and we've moved any necessary exports to a separate [@voiceflow/dtos-interact](https://www.npmjs.com/package/@voiceflow/dtos-interact) package as of [this release - `1.59.4`](https://github.com/voiceflow/react-chat/blob/master/packages/react-chat/CHANGELOG.md#1594-2024-09-11)
